=== sanchezregueroluisalberto/Apuntes/ApuntesLenguajedeMarcas/RELACION4/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agencia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paquetes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="paquete" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="destino" type="xs:string" />
                                        <xs:element name="precio">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minExclusive value="0" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fechaInicio" type="xs:date" />
                                        <xs:element name="fechaFin" type="xs:date" />
                                        <xs:element name="tipo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Aventura" />
                                                    <xs:enumeration value="Relax" />
                                                    <xs:enumeration value="Cultural" />
                                                    <xs:enumeration value="Familiar" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="clientes">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cliente" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre">
                                                                    <xs:simpleType>
                                                                        <xs:restriction
                                                                            base="xs:string">
                                                                            <xs:pattern
                                                                                value="[A-Z].*" />
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="dni">
                                                                    <xs:simpleType>
                                                                        <xs:restriction
                                                                            base="xs:string">
                                                                            <xs:pattern
                                                                                value="\d{8}[A-Z]" />
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="edad">
                                                                    <xs:simpleType>
                                                                        <xs:restriction
                                                                            base="xs:integer">
                                                                            <xs:minInclusive
                                                                                value="18" />
                                                                            <xs:maxInclusive
                                                                                value="99" />
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="email">
                                                                    <xs:simpleType>
                                                                        <xs:restriction
                                                                            base="xs:string">
                                                                            <!-- Email simple:
                                                                            usuario@dominio.tld -->
                                                                            <xs:pattern
                                                                                value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}" />
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="codigo" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <!-- Patrón: A seguido de 3 dígitos -->
                                                <xs:pattern value="PKT-\d{4}" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sanchezregueroluisalberto/Apuntes/ApuntesLenguajedeMarcas/RELACION4/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<agencia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio5.xsd">
    <paquetes>
        <paquete codigo="PKT-1234">
            <destino>Granada</destino>
            <precio>19.35</precio>
            <fechaInicio>2025-10-06</fechaInicio>
            <fechaFin>2025-10-06</fechaFin>
            <tipo>Aventura</tipo>
            <clientes>
                <cliente>
                    <nombre>Evaristo</nombre>
                    <dni>12345678X</dni>
                    <edad>25</edad>
                    <email>a@a.com</email>
                </cliente>
                <cliente>
                    <nombre>Evaristo</nombre>
                    <dni>12345678X</dni>
                    <edad>25</edad>
                    <email>a@a.com</email>
                </cliente>
            </clientes>
        </paquete>
        <paquete codigo="PKT-1234">
            <destino>Granada</destino>
            <precio>19.35</precio>
            <fechaInicio>2025-10-06</fechaInicio>
            <fechaFin>2025-10-06</fechaFin>
            <tipo>Aventura</tipo>
            <clientes>
                <cliente>
                    <nombre>Evaristo</nombre>
                    <dni>12345678X</dni>
                    <edad>25</edad>
                    <email>a@a.com</email>
                </cliente>
            </clientes>
        </paquete>
    </paquetes>
</agencia>
