=== sanchezregueroluisalberto/Apuntes/ApuntesLenguajedeMarcas/RELACION4/Ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="clase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumnos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumno" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>


                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z].*" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                        <xs:element name="edad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minExclusive value="6" />
                                                    <xs:maxExclusive value="18" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                        <xs:element name="notas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nota" minOccurs="1"
                                                        maxOccurs="5">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:float">
                                                                <xs:minInclusive value="0" />
                                                                <xs:maxExclusive value="10" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="dni">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{8}[A-Z]" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>


                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:positiveInteger" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sanchezregueroluisalberto/Apuntes/ApuntesLenguajedeMarcas/RELACION4/Ejercicio4.xml
<clase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio4.xsd">

    <alumnos>
        <alumno id="2">
            <nombre>Juan</nombre>
            <edad>9</edad>
            <notas>
                <nota>5</nota>
                <nota>7</nota>
            </notas>
            <dni>87654321Q</dni>
        </alumno>
        <alumno id="3">
            <nombre>Luis</nombre>
            <edad>10</edad>
            <notas>
                <nota>8</nota>
                <nota>7</nota>
            </notas>
            <dni>09876543Q</dni>
        </alumno>
    </alumnos>
</clase>
