<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipo [
<!ELEMENT equipo (pokemon+)>
<!ELEMENT pokemon (nombre, tipo*, nivel)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>

]>


<equipo>
    <pokemon>
        <nombre>pikachu</nombre>
        <tipo>electrico</tipo>
        <nivel>35</nivel>
    </pokemon>

     <pokemon>
        <nombre>Raichu</nombre>
        <tipo>electrico</tipo>
        <nivel>20</nivel>
    </pokemon>


</equipo>